/*
reCAPTCHA

Testing VerifyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package recaptcha

import (
	"context"
	"testing"

	openapiclient "github.com/pourcheragh/recaptcha-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_recaptcha_VerifyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VerifyAPIService SiteVerify", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.VerifyAPI.SiteVerify(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
